global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    monitor: "asus-router-monitor"

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s
    scrape_timeout: 10s

  # ASUS Router Exporter
  - job_name: "asus-router"
    static_configs:
      - targets: ["asus-exporter:8000"]
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics

  # Optional: Add more exporters here
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
